version: '3.3'
services:
  semkov-app:
    network_mode: host
    image: mantiby/semkov:latest
    container_name: semkov-app
    ports:
      - "8898:8898"
    volumes:
      - /home/manti/www/semkov-gorodok.by/src/:/srv/semkov/src/
      - /home/manti/www/semkov-gorodok.by/log/:/var/log/semkov/
      - /home/manti/www/semkov-gorodok.by/static/:/srv/semkov/static/
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
